version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
