version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "io.kubernetes:client-java"
        versions:
          - "*-legacy"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
