name: Build

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Install Skaffold
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            skaffold
          skaffold: 2.15.0
      - name: Build Images
        run: skaffold build --push=false --disable-multi-platform-build=true