name: OverallBuild

on:
  push:
    branches:
      - '**'

jobs:
  assembleWholeProject:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-assembleWholeProject-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-assembleWholeProject-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-assembleWholeProject-
          gradle-
    - name: Assemble
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        ./gradlew build
    - name: Archive test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: |
          */build/test-results
          */build/reports      
          build/test.org.modelix/TEST-jetbrains.mps.testbench.junit.suites.AntModuleTestSuite0-all.xml          
