name: Publish

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Use tag as version
        run: echo "${GITHUB_REF#refs/*/}" > version.txt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Install Skaffold
        uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          setup-tools: |
            skaffold
          skaffold: 2.15.0
      - name: Build and Push Images
        run: skaffold build --push --default-repo='docker.io/modelix' --tag='${GITHUB_REF#refs/*/}'
