name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  newRelease:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Use tag as version
      run: echo "${GITHUB_REF#refs/*/}" > modelix.version
    - name: Build and Publish Maven
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew assemble publish -Partifacts.itemis.cloud.user=${{secrets.ARTIFACTS_ITEMIS_CLOUD_USER}} -Partifacts.itemis.cloud.pw=${{secrets.ARTIFACTS_ITEMIS_CLOUD_PW}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
    - name: Build and Publish Docker
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./docker-ci.sh
    - name: Publish Helm Chart
      env:
        ARTIFACTS_ITEMIS_CLOUD_USER: ${{secrets.ARTIFACTS_ITEMIS_CLOUD_USER}}
        ARTIFACTS_ITEMIS_CLOUD_PW: ${{secrets.ARTIFACTS_ITEMIS_CLOUD_PW}}
      run: ./helm/publish.sh